# Generated by Django 6.0.1 on 2026-01-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pk'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
