# Generated by Django 6.0.1 on 2026-01-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/', verbose_name='Превью'),
        ),
    ]
